version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: weekly-activity-db
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: rootpassword
      POSTGRES_DB: activityhub
    ports:
      - '7001:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
